checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: true

enableHardenedMode: true

enableScripts: false

initScope: stream-io

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - stream-chat
  - stream-chat-react
  - stream-chat-react-native
  - stream-chat-react-native-core
  - "@skooldev/skool-stream-layout"

npmPublishProvenance: true

yarnPath: .yarn/releases/yarn-4.15.0.cjs
