// Vendors the React Native design tokens generated by the design-system-tokens repo into
// `src/theme/tokens/`, adding a banner and reformatting to this repo's Prettier style.
//
// The generated files are checked in on purpose: the SDK must build without the tokens repo
// present. Re-run this after regenerating tokens (`npm run build:reactnative` over there).
//
// Usage:
//   yarn sync:tokens                       # uses ../../../design-system-tokens
//   yarn sync:tokens --from <build/reactnative dir>
//   STREAM_DESIGN_TOKENS=<repo or build dir> yarn sync:tokens
import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = resolve(scriptDir, '..');
const repoRoot = resolve(packageDir, '..', '..');
const targetDir = join(packageDir, 'src', 'theme', 'tokens');

const THEMES = ['light', 'dark'] as const;
const PLATFORMS = ['ios', 'android', 'web'] as const;
/**
 * The platform whose file `StreamTokens.ts` re-exports, for bundlers and type-checkers that do not
 * understand React Native platform extensions.
 */
const FALLBACK_PLATFORM = 'ios';
const TYPES_FILE = 'StreamTokens.types.ts';

const parseArgs = (argv: string[]): string | undefined => {
  const index = argv.indexOf('--from');
  return index === -1 ? undefined : argv[index + 1];
};

/** Accepts either the tokens repo root or its `build/reactnative` directory. */
const resolveSourceDir = async (): Promise<string> => {
  const candidates = [
    parseArgs(process.argv.slice(2)),
    process.env.STREAM_DESIGN_TOKENS,
    join(repoRoot, '..', 'design-system-tokens'),
  ].filter((candidate): candidate is string => Boolean(candidate));

  for (const candidate of candidates) {
    const base = resolve(candidate);
    const withSuffix = join(base, 'build', 'reactnative');
    if (existsSync(join(base, TYPES_FILE))) return base;
    if (existsSync(join(withSuffix, TYPES_FILE))) return withSuffix;
  }

  throw new Error(
    `Could not find generated React Native tokens. Looked in:\n` +
      candidates.map((c) => `  - ${resolve(c)}`).join('\n') +
      `\nRun \`npm run build:reactnative\` in the design-system-tokens repo, ` +
      `then pass --from <dir> if it lives elsewhere.`,
  );
};

const banner = (sourceLabel: string): string =>
  `// Vendored from the design-system-tokens repo (${sourceLabel}).\n` +
  `// Do not edit by hand: run \`yarn sync:tokens\` in packages/react-native-sdk.\n`;

const format = async (contents: string, filepath: string): Promise<string> => {
  const options = await prettier.resolveConfig(filepath);
  return prettier.format(contents, { ...options, filepath });
};

const write = async (filepath: string, contents: string): Promise<void> => {
  await mkdir(dirname(filepath), { recursive: true });
  await writeFile(filepath, await format(contents, filepath), 'utf8');
};

/**
 * Fails loudly on the one thing that silently breaks at runtime: a token group referencing a group
 * that is declared after it in the same module.
 */
const assertNoForwardReferences = (contents: string, file: string): void => {
  const groups = [...contents.matchAll(/^export const (\w+)/gm)].map(
    (match) => ({ name: match[1], index: match.index ?? 0 }),
  );
  for (const [position, group] of groups.entries()) {
    const end = groups[position + 1]?.index ?? contents.length;
    const body = contents.slice(group.index, end);
    for (const later of groups.slice(position + 1)) {
      if (new RegExp(`\\b${later.name}\\.`).test(body)) {
        throw new Error(
          `${file}: group "${group.name}" references "${later.name}", which is ` +
            `declared later in the file. That throws at module evaluation time.`,
        );
      }
    }
  }
};

const main = async (): Promise<void> => {
  const sourceDir = await resolveSourceDir();
  const sourceLabel = sourceDir.replace(resolve(repoRoot, '..'), '..');
  const written: string[] = [];

  const types = await readFile(join(sourceDir, TYPES_FILE), 'utf8');
  await write(join(targetDir, TYPES_FILE), `${banner(sourceLabel)}\n${types}`);
  written.push(TYPES_FILE);

  for (const theme of THEMES) {
    const themeDir = join(sourceDir, theme);
    const available = existsSync(themeDir) ? await readdir(themeDir) : [];

    for (const platform of PLATFORMS) {
      const filename = `StreamTokens.${platform}.ts`;
      if (!available.includes(filename)) {
        throw new Error(`Missing ${theme}/${filename} in ${sourceDir}`);
      }
      const contents = await readFile(join(themeDir, filename), 'utf8');
      assertNoForwardReferences(contents, `${theme}/${filename}`);
      await write(
        join(targetDir, theme, filename),
        `${banner(sourceLabel)}\n${contents}`,
      );
      written.push(`${theme}/${filename}`);
    }

    await write(
      join(targetDir, theme, 'StreamTokens.ts'),
      `${banner(sourceLabel)}\nexport * from './StreamTokens.${FALLBACK_PLATFORM}';\n`,
    );
    written.push(`${theme}/StreamTokens.ts`);
  }

  console.log(`Synced ${written.length} files from ${sourceDir}:`);
  written.forEach((file) => console.log(`  ${file}`));
};

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
