name: Deploy Egress-Composite
on:
  push:
    branches:
      - main
      - egress-composite
    paths:
      - packages/egress-composite/**
      - packages/client/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build:client && yarn build:egress

      - name: Upload Egress Composite GH Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './packages/egress-composite/dist/'

  deploy-egress-composite:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Egress Composite
        uses: actions/deploy-pages@v1

