name: Test
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STREAM_API_KEY: ${{ vars.CLIENT_TEST_API_KEY }}
  STREAM_SECRET: ${{ secrets.CLIENT_TEST_SECRET }}

on:
  # Trigger flow when pushing in main or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: ESLint Cache
        uses: actions/cache@v4
        with:
          path: './.eslintcache'
          key: ${{ runner.os }}-eslintcache-${{ github.ref_name }}-${{ hashFiles('.eslintcache') }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Packages
        run: yarn lint:ci:all

      - name: Test packages
        run: yarn test:ci:all

      - name: Test RN SDK
        run: yarn test:react-native:sdk

      - name: Build packages
        run: NODE_ENV=production yarn build:all
