name: Test and deploy dogfood
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

on:
  # Trigger flow when pushing in main or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: ESLint Cache
        uses: actions/cache@v3
        with:
          path: './.eslintcache'
          key: ${{ runner.os }}-eslintcache-${{ github.ref_name }}-${{ hashFiles('.eslintcache') }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Packages
        run: yarn lint:ci:all

      - name: Build packages
        run: NODE_ENV=production yarn build:all

      - name: Test packages
        run: yarn test:ci:all

      # Vercel deployment: Dogfood (Preview)
      - name: Vercel Pull Configuration Dogfood (Preview)
        if: ${{ github.base_ref == 'main' }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Vercel Build Dogfood (Preview)
        if: ${{ github.base_ref == 'main' }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Vercel Deploy Dogfood (Preview)
        if: ${{ github.base_ref == 'main' }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      # Vercel deployment Dogfood (Production)
      - name: Vercel Pull Configuration Dogfood (Production)
        if: ${{ github.ref_name == 'main' }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Vercel Build Dogfood (Production)
        if: ${{ github.ref_name == 'main' }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: yarn vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Vercel Deploy Dogfood (Production)
        if: ${{ github.ref_name == 'main' }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: yarn vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Test RN SDK
        run: yarn test:react-native:sdk

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
