name: Test and release
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint Packages
        run: yarn lint:ci:all

      - name: Build packages
        run: yarn build:all

      - name: Test packages
        run: yarn test:ci:all

      - name: Release packages
        run: echo 'TODO'

      - name: Deploy Stream Calls to Vercel
        run: |
          npx vercel pull --cwd=./packages/react-dogfood --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel deploy --cwd=./packages/react-dogfood --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
